chapters="
./abramhindle/energymining.md
./ajko/deployment-chapter.md
./alexorso/are-we-helping-developers.md
./alexorso/something-wrong-with-the-universe.md
./andreas-zeller/appmining.md
./andymeneely/actionable.md
./andymeneely/security_gotchas.md
./anikora/chapter.md
./baishakhir/language-chapter.md
./bener/ayse1.md
./bmurphy/chapter.md
./cabird/bias-chapter.md
./cabird/interviews.md
./dspinellis/tools.md
./dyba-bergersen-sjoberg/EMSE.md
./dyba-bergersen-sjoberg/WhyYouShouldUseTheory.md
./ermurph/survey-chapter.md
./etbarr/naturalness.md
./fayola21/goldilocks.md
./menzies/CorrelationVsCausation.md
./menzies/dagstuhlManifesto.md
./menzies/inductiveManifesto.md
./gmurphy/logitall.md
./gousiosg/open-from-the-beginning.md
./GunetherRuhe/RuheNayebi.md
./hongyu/DemocratizingData.md
./hongyu/SuccessStory.md
./jacekczerwonka/code_reviews.md
./jeffhuang/GameOfData.md
./just_herzig/bug_report_gotchas.md
./kim_herzig/test_data.md
./mastorey/bigdataneedsthickdata.md
./mdipenta/mdipenta-quant-qual.md
./meinagappan/Diversity_in_SE_Research.md
./meinagappan/miningmobileappstores.md
./bramadams/releng.md
./brusso/NeedsDataAnalysisPattern.md
./budgen/eb-decision.md
./mikegodfrey/provenanceChapter.md
./minkull/ensembles.md
./minkull/learning-styles.md
./minkull/readme.md
./miryungkim/datascientists.md
./mjshepperd/chapter.md
./zimmermann/card-sorting.md
./zimmermann/no-one-size-fits-all.md
./obaysal/personalization-chapter.md
./oivo/bringData.md
./pgbovine/PreppingData.md
./prechelt/learn-from-failure.md
./rotella/AdvancesReleaseReadiness.md
./rrobbes/smallcompanies.md
./rtholmes/summarizing-dynamic-data.md
./ruhe/WhatCountsIsDecisionsNotNumbers.md
./runeson/Plea4vis-v1.md
./sback/summarizing-unstructured-data.md
./siravegas/Challenges SE Experiments.md
./stephan_diehl/visualization.md
./tomFr/measuringProd.md
./trevorcarnahan/Reducing Time to Insight.md
./turhanb/theGraph.md
./venkatesh-prasad-ranganath/embraceDynamicArtifacts.md
./venkatesh-prasad-ranganath/simpleExplanationsAreBetter.md
./wagnerst/text-mining.md
./weyuker-ostrand/prediction.md
./whitehead/whitehead-from-data-to-theory.md
./zhang-xie/SoftwareAnalyticsInPractice.md
./muench/Chapter_Muench.md
./natalia-juristo/Reproducible results.md
"

for ch in $chapters; do
	gh is --new --title "$ch" --message "After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'." --user ds4se --repo chapters --label reviewOne
done
